% SETMATCHDEFAULTS - restore default match settings
%
% This method restores default match settings
%
% Usage:
%   >> obj = setMatchDefaults(obj)
%
% created March, 2026 by Nathan Brown (Sandia National Laboratories)
%
function obj = setMatchDefaults(obj)

obj.match = struct; % delete any old stuff
obj = resetMatch(obj); % empty containers

obj.match.centroids.roiSelect = 'manual';
obj.match.centroids.roiNum = 5;
obj.match.centroids.threshFrac = 0.5;
obj.match.centroids.poiType = 'mean';
obj.match.centroids.filterBounds = 'none';
obj.match.centroids.orientationSearchBound = 180*ones(1,3);
obj.match.centroids.mosaicitySearchBound = 9*ones(1,3);
obj.match.centroids.gaOpts = optimoptions('ga', 'Display', 'iter', ...
    'PlotFcn', {}, 'UseVectorized', false, ...
    'UseParallel', true, ...
    'FunctionTolerance',1e-3, 'MaxStallGenerations', 10, ...
    'PopulationSize', 1e4, ...
    'MutationFcn', 'mutationadaptfeasible', ...
    'CrossoverFcn', {@crossoverintermediate, 1}, ...
    'CrossoverFraction', 0.5, ...
    'MaxTime', inf, ...
    'MaxGenerations', inf, ...
    'OutputFcn', @centroidsOut);
obj.match.centroids.scoreFunction = struct(...
    'name', 'defaultScoreFcn', ...
    'penaltyFactor', 1, ...
    'intensityCutoff', 0.01, ...
    'badDistance', 0.05, ...
    'worstDistanceRatio', 2);

obj.match.image.target = -1;
obj.match.image.orientationSearchBound = 5*ones(1,3);
obj.match.image.mosaicitySearchBound = 5*ones(1,3);
obj.match.image.gaussianSpreadBound = 0;
obj.match.image.volumeRatioBound = 0;
obj.match.image.minSpotPixels = 5e-5;
obj.match.image.minCCFilterSize = obj.match.image.minSpotPixels/10;
obj.match.image.intensityPercentile = 0.9;
obj.match.image.weightScheme = 'ranksqrt';
obj.match.image.overlapDistance = 0.01;
obj.match.image.gaOpts = optimoptions('ga', 'Display', 'iter', ...
        'PlotFcn', {}, 'UseVectorized', false, ...
        'FunctionTolerance', 1e-3, 'MaxStallGenerations', 10, ...
        'PopulationSize', 1e4, ...
        'MutationFcn', 'mutationadaptfeasible', ...
        'CrossoverFcn', {@crossoverintermediate, 1}, ...
        'CrossoverFraction', 0.5, ...
        'UseParallel',true, ...
        'MaxTime', 24*3600, ...
        'MaxGenerations', inf, ...
        'OutputFcn', @imageOut);
obj.match.image.scoreFunction = struct(...
    'name', 'defaultScoreFcn', ...
    'metricWeights', [1 3 1], ...
    'badDistance', 0.05);
end

%% custom GA output functions

% image

function [state,options,optchanged]=imageOut(options,state,flag)
optchanged = false;
str = ['This file keeps track of the best population ', ...
    'in case the optimization is prematurely ended before the solution ', ...
    'is recorded in the output object.'];
str = [string(str); string(['Manually implement by adding each orientation ', ...
    'and mosaicity to its respective centroid solution.'])];
str = [string(str); "--> Check matchImage for implementation details."];
fname = 'backup.txt';
switch flag
    case 'init'
        fprintf('\nPopulation Size of %d\n', options.PopulationSize); 
        writelines(str,fname,'WriteMode','overwrite');
    case 'iter'
        if state.LastImprovement == state.Generation
            str = [str; string(sprintf('Score: %.4f', state.Best(end)))];
            [~, ind] = min(state.Score);
            pop = state.Population(ind,:);
            for ii = 1:floor(numel(pop)/6)
                z = (ii-1)*6;
                str = [str; string(sprintf(...
                    'Orientation Add %d: %.4f  %.4f  %.4f', ii, ...
                    pop(z+1), pop(z+2), pop(z+3)))];
                str = [str; string(sprintf(...
                    'Mosaicity Add %d: %.4f  %.4f  %.4f', ii, ...
                    pop(z+4), pop(z+5), pop(z+6)))];
            end
            str = [str; string(sprintf(...
                'Broadening Add: %.4f', pop(end-1)))];
            str = [str; string(sprintf(...
                'Volume Ratio Multiplier: %.4f', pop(end)))];
            writelines(str, fname, 'WriteMode', 'overwrite');
        end     
end

end

% centroids

function [state,options,optchanged]=centroidsOut(options,state,flag)
optchanged = false;
str = ['This file keeps track of the best population ', ...
    'in case the optimization is prematurely ended before the solution ', ...
    'is recorded in the output object.'];
str = [string(str); string(['Manually implement by adding each orientation ', ...
    'and mosaicity to the starting values and then setting the centroids solutions.'])];
str = [string(str); "--> Check matchCentroids and changeObject for implementation details."];
fname = 'backup.txt';
switch flag
    case 'init'
        fprintf('\nPopulation Size of %d\n', options.PopulationSize); 
        writelines(str,fname,'WriteMode','overwrite');
    case 'iter'
        if state.LastImprovement == state.Generation
            str = [str; string(sprintf('Score: %.4f', state.Best(end)))];
            [~, ind] = min(state.Score);
            pop = state.Population(ind,:);
            z = 0;
            str = [str; string(sprintf(...
                'Orientation Add: %.4f  %.4f  %.4f', ...
                pop(z+1), pop(z+2), pop(z+3)))];
            str = [str; string(sprintf(...
                'Mosaicity Add: %.4f  %.4f  %.4f', ...
                pop(z+4), pop(z+5), pop(z+6)))];
            writelines(str, fname, 'WriteMode', 'overwrite');
        end     
end

end